version: '3.8'

services:
  api-chamados:
    build: .
    container_name: api-chamados-node
    restart: always
    ports:
      - '4000:3000'
    env_file:
      - .env
    depends_on:
      - db-chamados

  db-chamados:
    image: mysql:8.0
    container_name: db-chamados-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE}
    ports:
      - '3308:3306'
    volumes:
      - chamados_db_data:/var/lib/mysql

volumes:
  chamados_db_data:
